create external table if not exists wzwd.wzwd_ods_game_AllFrameTable_d (
    nm_version_p            STRING COMMENT '一次模拟的版本号。分区字段（冗余）',
    list_version            STRING COMMENT 'list文件推断的版本',
    proc_version            STRING COMMENT '一次模拟中，代表着第几次处理的版本号',
    bd_A_index            CHAR(10) COMMENT 'A阵容索引',
    bd_B_index            CHAR(10) COMMENT 'B阵容索引',
    random_seed           INT COMMENT '随机种子',
    result                INT COMMENT '战斗结果',
    last_time             DOUBLE COMMENT '战斗持续时长',
    frame                 INT COMMENT '帧号',
    AD                 DOUBLE COMMENT '物理伤害',
    ADMultiplier                 DOUBLE COMMENT '',
    ADReduction                 DOUBLE COMMENT 'AD减伤',
    AD_IMMUNE                 DOUBLE COMMENT '',
    APMultiplier                 DOUBLE COMMENT '',
    APReduction                 DOUBLE COMMENT '受AD减伤',
    AP_IMMUNE                 DOUBLE COMMENT '',
    AntiCrit                 DOUBLE COMMENT '抗暴',
    AntiDamage                 DOUBLE COMMENT '反伤比例',
    Aspd                 DOUBLE COMMENT '攻击攻速',
    Combat                 DOUBLE COMMENT '战力=生命*1 + 攻击*20 + 命中*81 + 闪避*81 + 物理软防*20 + 物理硬防*25 + 暴击率*62 + 爆伤*62',
    Crit                 DOUBLE COMMENT '暴击',
    CritDamage                 DOUBLE COMMENT '',
    DamageAbsorbRate                 DOUBLE COMMENT '',
    DamageMultiplier                 DOUBLE COMMENT '',
    DamageReduction                 DOUBLE COMMENT '',
    Def                 DOUBLE COMMENT '防御',
    DefBreak                 DOUBLE COMMENT '',
    Elements                 STRING COMMENT '五行',
    Flee                 DOUBLE COMMENT '闪避',
    HP                 DOUBLE COMMENT '',
    HPRegeneration                 DOUBLE COMMENT '帧号',
    Hast                 DOUBLE COMMENT '急速',
    HealRate                 DOUBLE COMMENT '',
    Hit                 DOUBLE COMMENT '命中',
    Insight                 DOUBLE COMMENT '洞察',
    LifeSteal                 DOUBLE COMMENT '',
    MP                 DOUBLE COMMENT '能量',
    MPReductionRate                 DOUBLE COMMENT '',
    MPRegeneration                 DOUBLE COMMENT '',
    MaxHP                 DOUBLE COMMENT '最大生命值。会在战斗中变化，比如周池能永久提升自身最大生命值',
    Mdef                 DOUBLE COMMENT '魔法防御',
    MdefBreak                 DOUBLE COMMENT '',
    PerfectDodge                 DOUBLE COMMENT '必闪',
    S1Level                 DOUBLE COMMENT '',
    S2Level                 DOUBLE COMMENT '',
    SkillDamageEnhancement                 DOUBLE COMMENT '',
    SkillDamageReduction                 DOUBLE COMMENT '',
    SkinID                 BIGINT COMMENT '',
    Speed                 DOUBLE COMMENT '移动速度',
    TakeHealRate                 DOUBLE COMMENT '',
    TakeMPRate                 DOUBLE COMMENT '',
    Toughness                 DOUBLE COMMENT '韧性',
    display_script_name                 STRING COMMENT '',
    isCopyActor                 INT COMMENT '',
    wuxing int comment '五行（新）',
    BuffEffects                 STRING COMMENT '角色的buff状态列表，用竖线分隔，枚举值含义见：1.字典信息',
    Buffs                 STRING COMMENT '',
    CardName                 STRING COMMENT '角色姓名',
    Direction                 INT COMMENT '朝向。开局时左队伍是1右队伍是-1',
    FightActorId                 BIGINT COMMENT '角色ID',
    Pos1                 DOUBLE COMMENT 'x坐标',
    Pos2                 DOUBLE COMMENT 'y坐标',
    Side                 INT COMMENT '阵营。左1右-1',
    State                 INT COMMENT '角色状态。击飞，恐惧等，枚举值含义见：1.字典信息',
    ViperCount                 INT COMMENT '帧号',
    ActorType int comment '',
    Id int comment '',
    shield int comment '护盾',
    Pos String comment '坐标集合（1代表x坐标，2代表y坐标）'
)
    COMMENT '每帧状态日志'
    PARTITIONED BY (nm_version STRING)
    ROW FORMAT DELIMITED
        FIELDS TERMINATED BY '\001'
        COLLECTION ITEMS TERMINATED BY '\002'
        MAP KEYS TERMINATED BY '\003'
    STORED AS TEXTFILE
    LOCATION '/staging/wzwd/nm/k8s/AllFrameTable';

ALTER TABLE wzwd.wzwd_ods_game_AllFrameTable_d add if not exists PARTITION(nm_version='${nm_version}')
    LOCATION '/staging/wzwd/nm/k8s/AllFrameTable/${nm_version}';